# **XI. Model Inference**

## Import Libraries

In [15]:
import pickle
import json
import pandas as pd
import numpy as np

## Load Model

In [16]:
# Load Model

# Modelling
with open('ab_model.pkl', 'rb') as file_1:
    ab_model = pickle.load(file_1)


# Pre-processing

with open('scale_feat.pkl', 'rb') as file_2:
    scale_feat = pickle.load(file_2)

with open('winsoriser.pkl', 'rb') as file_3:
    winsoriser = pickle.load(file_3)
    
# List Numeric & Category
with open('num_cols_sc.txt', 'r') as file_4:
    num_cols_sc = json.load(file_4)
    
with open('num_cols_nsc.txt', 'r') as file_5:
    num_cols_nsc = json.load(file_5)

## Inferencing

In [17]:
# Me-loading data
data = pd.read_csv('D:\RAKA\DATA SCIENCE\HACKTIVE8\Dataset GC\h8dsft_P1M1_Muhammad Farhan Darmawan.csv')

In [18]:
df_inf = data.sample(n = 20)
df_inf

,limit_balance,sex,education_level,marital_status,age,pay_0,pay_2,pay_3,pay_4,pay_5,...,bill_amt_4,bill_amt_5,bill_amt_6,pay_amt_1,pay_amt_2,pay_amt_3,pay_amt_4,pay_amt_5,pay_amt_6,default_payment_next_month
1667,50000.0,1,2,2,30.0,0.0,0.0,0.0,0.0,0.0,...,2207.0,0.0,0.0,2000.0,2000.0,1000.0,0.0,0.0,0.0,0
2181,110000.0,1,1,1,40.0,1.0,-2.0,-1.0,0.0,-1.0,...,2000.0,216.0,216.0,0.0,2066.0,0.0,216.0,216.0,66.0,1
1315,260000.0,1,3,1,36.0,-1.0,0.0,0.0,0.0,0.0,...,73658.0,70273.0,67100.0,7425.0,2795.0,2779.0,2947.0,3400.0,5000.0,0
2488,240000.0,2,1,2,25.0,1.0,-1.0,-1.0,-1.0,-1.0,...,2417.0,0.0,0.0,587.0,0.0,2417.0,0.0,0.0,7642.0,0
895,80000.0,2,2,3,52.0,0.0,0.0,0.0,0.0,0.0,...,50345.0,52031.0,53141.0,2087.0,2019.0,2000.0,2500.0,2095.0,2002.0,0
1035,80000.0,2,2,2,23.0,2.0,0.0,0.0,0.0,0.0,...,33336.0,24439.0,26187.0,3139.0,4000.0,3000.0,2000.0,2000.0,0.0,1
1374,400000.0,2,1,1,28.0,-1.0,-1.0,2.0,0.0,0.0,...,392932.0,394410.0,410127.0,405016.0,0.0,14000.0,13560.0,28000.0,0.0,0
2116,30000.0,2,2,1,39.0,-1.0,3.0,2.0,0.0,-1.0,...,780.0,2057.0,1737.0,0.0,0.0,0.0,2057.0,0.0,0.0,0
240,250000.0,2,1,2,31.0,0.0,0.0,0.0,0.0,0.0,...,68165.0,68787.0,70111.0,3500.0,2658.0,3000.0,4000.0,3000.0,2500.0,0
2832,220000.0,1,1,1,36.0,-1.0,-1.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,863.0,0
2796,300000.0,1,1,1,45.0,1.0,-2.0,-2.0,-2.0,-2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2235,250000.0,1,1,1,41.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,28790.0,4418.0,10676.0,10957.0,4614.0,28796.0,4418.0,10676.0,0.0,0
2317,150000.0,2,2,1,28.0,0.0,-1.0,-1.0,-1.0,-1.0,...,430.0,840.0,430.0,850.0,850.0,430.0,840.0,430.0,860.0,1
1486,70000.0,2,3,1,35.0,3.0,2.0,2.0,2.0,0.0,...,27590.0,27850.0,28085.0,0.0,2708.0,0.0,1010.0,1013.0,2000.0,1
698,90000.0,2,2,2,23.0,0.0,0.0,0.0,0.0,0.0,...,91343.0,90887.0,90858.0,4200.0,4100.0,3307.0,3405.0,3311.0,6204.0,0
208,90000.0,2,1,2,29.0,0.0,0.0,0.0,0.0,0.0,...,91297.0,91790.0,91377.0,3600.0,4331.0,3218.0,3613.0,3300.0,3519.0,0
2521,50000.0,2,2,2,38.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,390.0,390.0,390.0,390.0,390.0,390.0,390.0,390.0,390.0,0
261,90000.0,2,1,2,33.0,0.0,0.0,0.0,0.0,0.0,...,61755.0,63629.0,54423.0,2100.0,4000.0,3000.0,3000.0,2323.0,2000.0,0
2471,100000.0,2,1,2,37.0,-1.0,-1.0,0.0,-1.0,-1.0,...,780.0,0.0,0.0,21711.0,1000.0,780.0,0.0,0.0,0.0,0
696,260000.0,2,2,2,24.0,0.0,0.0,0.0,0.0,0.0,...,50998.0,53835.0,56728.0,2500.0,4000.0,4000.0,3835.0,3805.0,3000.0,0

In [19]:
# Mengambil data yang digunakan
df_inf = df_inf.drop(['default_payment_next_month'], axis = 1)

Handling Cardinality

In [20]:
# Handling cardinality
df_inf = df_inf.replace({'education_level' : {1 : 1, 2 : 2, 3 : 3, 4 : 4, 5 : 4, 6 : 4, 0 :4}, 
                           'marital_status' : {1 : 1, 2 : 2, 3 : 3, 0 : 3},
                           'pay_0' : {-2 : 0, -1 : 0},
                           'pay_2' : {-2 : 0, -1 : 0},
                           'pay_3' : {-2 : 0, -1 : 0},
                           'pay_4' : {-2 : 0, -1 : 0},
                           'pay_5' : {-2 : 0, -1 : 0},
                           'pay_6' : {-2 : 0, -1 : 0}})

Handling Outlier

In [21]:
df_inf_t = winsoriser.transform(df_inf)

Splitting data by list

In [22]:
df_inf_sc = df_inf_t[num_cols_sc]
df_inf_nsc = df_inf_t[num_cols_nsc]

Feature Scaling

In [23]:
df_inf_sc = scale_feat.transform(df_inf_sc)

In [24]:
df_inf_sc = pd.DataFrame(df_inf_sc, columns = num_cols_sc)

In [25]:
# Reset Index
df_inf_sc.reset_index(drop= True, inplace= True)
df_inf_nsc.reset_index(drop = True, inplace = True)

In [26]:
df_final = pd.concat([df_inf_nsc, df_inf_sc], axis= 1)

In [27]:
df_final = df_final.loc[:,['pay_0', 'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6', 'limit_balance', 
                                     'pay_amt_1', 'pay_amt_2', 'pay_amt_3', 'pay_amt_4', 'pay_amt_5', 'pay_amt_6']]

Modeling

In [28]:
y_pred_inf = ab_model.predict(df_final)
y_pred_inf

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
      dtype=int64)